// Copyright 2025 go-dataspace
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package dsp.v1alpha2;

// The ContractService allows RUN-DSP to call an external service to approve/terminate contract
// negotiation steps.
// Outside of the defined calls, RUN-DSP will also forward the `authorization` header so that
// the caller can be verified by the service.
service ContractService {
  // Configure sets some callback configuration parameters.
  rpc Configure(ContractServiceConfigureRequest) returns (ContractServiceConfigureResponse) {}
  // RequestReceived is called when RUN-DSP receives a ContractRequestMessage.
  rpc RequestReceived(ContractServiceRequestReceivedRequest) returns (ContractServiceRequestReceivedResponse) {}
  // OfferReceived is called when RUN-DSP receives a ContractOfferMessage.
  rpc OfferReceived(ContractServiceOfferReceivedRequest) returns (ContractServiceOfferReceivedResponse) {}
  // AcceptedReceived is called when RUN-DSP receives an Accepted event message.
  rpc AcceptedReceived(ContractServiceAcceptedReceivedRequest) returns (ContractServiceAcceptedReceivedResponse) {}
  // AgreementReceived is called when RUN-DSP receives a ContractAgreementMessage.
  rpc AgreementReceived(ContractServiceAgreementReceivedRequest) returns (ContractServiceAgreementReceivedResponse) {}
  // VerificationReceived is called when RUN-DSP receives a ContractVerificationMessage.
  rpc VerificationReceived(ContractServiceVerificationReceivedRequest) returns (ContractServiceVerificationReceivedResponse) {}
  // FinalizationReceived is called when RUN-DSP receives a Finalized event message.
  rpc FinalizationReceived(ContractServiceFinalizationReceivedRequest) returns (ContractServiceFinalizationReceivedResponse) {}
  // TerminationReceived is called when RUN-DSP receives a ContractTerminationMessage
  rpc TerminationReceived(ContractServiceTerminationReceivedRequest) returns (ContractServiceTerminationReceivedResponse) {}
}

// ContractServiceConfigureRequest represents the configuration request RUN-DSP does to the contract service.
message ContractServiceConfigureRequest {
  string connector_address = 1; // The gRPC address RUN-DSP will listen to for control directives.
  string verification_token = 2; // The verification token generated by RUN-DSP to use when we are verifying the above address.
}

message ContractServiceConfigureResponse {}

// ContractServiceRequestReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation and offer contains
// the raw JSON of the offer ODRL.
message ContractServiceRequestReceivedRequest {
  string pid = 1;
  string offer = 2;
}

message ContractServiceRequestReceivedResponse {}

// ContractServiceOfferReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation and the raw ODRL offer JSON.
message ContractServiceOfferReceivedRequest {
  string pid = 1;
  string offer = 2;
}

message ContractServiceOfferReceivedResponse {}

// ContractServiceAcceptedReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation that just got accepted.
message ContractServiceAcceptedReceivedRequest {
  string pid = 1;
}

message ContractServiceAcceptedReceivedResponse {}

// ContractServiceAgreementReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation that just got agreed to.
message ContractServiceAgreementReceivedRequest {
  string pid = 1;
  string agreement = 2;
}

message ContractServiceAgreementReceivedResponse {}

// ContractServiceVerificationReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation that just verified to.
message ContractServiceVerificationReceivedRequest {
  string pid = 1;
}

message ContractServiceVerificationReceivedResponse {}

// ContractServiceFinalizationReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation that just got finalized.
message ContractServiceFinalizationReceivedRequest {
  string pid = 1;
}

message ContractServiceFinalizationReceivedResponse {}

// ContractServiceTerminationReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation got terminated.
// It also contains the reason for said termination.
message ContractServiceTerminationReceivedRequest {
  string pid = 1;
  string code = 2;
  repeated string reason = 3;
}

message ContractServiceTerminationReceivedResponse {}
