// Copyright 2024 go-dataspace
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package dsp.v1alpha2;

import "dsp/v1alpha2/types.proto";

// ControlService contains methods that are not specific to catalogue, contract, or transfer operations.
// Configuration, and convenience methods will be put here.
service ControlService {
  // Publishes a dataset,
  rpc GetProviderDatasetDownloadInformation(GetProviderDatasetDownloadInformationRequest) returns (GetProviderDatasetDownloadInformationResponse) {}

  // VerifyConnection takes a token and verifies it's the same token it passed to the contract service.
  rpc VerifyConnection(VerifyConnectionRequest) returns (VerifyConnectionResponse) {}

  // Gets the catalogue based on the query parameters and the authorization header.
  rpc GetProviderCatalogue(GetProviderCatalogueRequest) returns (GetProviderCatalogueResponse) {}
  // Gets information about a single dataset.
  rpc GetProviderDataset(GetProviderDatasetRequest) returns (GetProviderDatasetResponse) {}

  // ContractRequest sends a ContractRequestMessage.
  rpc ContractRequest(ContractRequestRequest) returns (ContractRequestResponse) {}
  // ContractOffer sends a ContractOfferMessage.
  rpc ContractOffer(ContractOfferRequest) returns (ContractOfferResponse) {}
  // ContractAccept sends an accepted event message.
  rpc ContractAccept(ContractAcceptRequest) returns (ContractAcceptResponse) {}
  // ContractAgree sends a ContractAcceptedMessage.
  rpc ContractAgree(ContractAgreeRequest) returns (ContractAgreeResponse) {}
  // ContractVerify sends a ContractVerificationMessage.
  rpc ContractVerify(ContractVerifyRequest) returns (ContractVerifyResponse) {}
  // ContractFinalize sends a finalization event.
  rpc ContractFinalize(ContractFinalizeRequest) returns (ContractFinalizeResponse) {}
  // ContractTerminate sends a ContractTerminationMessage.
  rpc ContractTerminate(ContractTerminateRequest) returns (ContractTerminateResponse) {}

  // Tells provider that we have finished our transfer.
  rpc SignalTransferComplete(SignalTransferCompleteRequest) returns (SignalTransferCompleteResponse) {}
  // Tells provider to cancel file transfer
  rpc SignalTransferCancelled(SignalTransferCancelledRequest) returns (SignalTransferCancelledResponse) {}
  // Tells provider to suspend file transfer
  rpc SignalTransferSuspend(SignalTransferSuspendRequest) returns (SignalTransferSuspendResponse) {}
  // Tells provider to resume file transfer
  rpc SignalTransferResume(SignalTransferResumeRequest) returns (SignalTransferResumeResponse) {}
}

// VerifyConnectionRequest contains a verification token that can be compared to the one locally generated.
message VerifyConnectionRequest {
  string verification_token = 1;
}

message VerifyConnectionResponse {}

// GetProviderCatalogueRequest represents the parameters for the GetProviderCatalogue request
message GetProviderCatalogueRequest {
  string provider_uri = 1;
  // query_parameters is just a key/value map. These are not specified in the dataspace standard.
  // RUN-DSP also does not define them yet, so for now this is a placeholder.

  map<string, string> query_parameters = 2;
}

// GetProviderCatalogueResponse returns all the datasets matched by GetProviderCatalogue.
message GetProviderCatalogueResponse {
  repeated Dataset datasets = 1;
}

// GetProviderDatasetRequest contains the dataset ID.
message GetProviderDatasetRequest {
  string provider_url = 1;
  string dataset_id = 2;
}

// GetProviderDatasetResponse contains the requested dataset.
message GetProviderDatasetResponse {
  string provider_url = 1;
  Dataset dataset = 2;
}

// GetProviderDatasetDownloadInformationRequest contains the ID for the dataset
// we want to be able to download.
message GetProviderDatasetDownloadInformationRequest {
  string provider_url = 1;
  string dataset_id = 2;
}

// GetProviderDatasetDownloadInformationResponse contains the information needed
// to download a file, including authentication etc.
message GetProviderDatasetDownloadInformationResponse {
  PublishInfo publish_info = 1;
  string transfer_id = 2;
}

// ContractRequestRequest contains the offer, and a pid if this is needs to send a request for an already
// existing offer, or a participant_address if this is a request for a new offer.
message ContractRequestRequest {
  string offer = 1;
  optional string pid = 2;
  optional string participant_address = 3;
  bool auto_accept = 4;
  bool want_notifications = 5;
}

message ContractRequestResponse {}

// ContractOfferRequest contains the offer, and a pid if this is needs to send an offer for an already
// existing offer, or a participant_address if this is a a new offer.
message ContractOfferRequest {
  string offer = 1;
  optional string pid = 2;
  optional string participant_address = 3;
  bool auto_accept = 4;
  bool want_notifications = 5;
}

message ContractOfferResponse {}

// ContractAcceptRequest contains the pid of the contract negotiation to be accepted.
message ContractAcceptRequest {
  string pid = 1;
  bool auto_accept = 2;
  bool want_notifications = 3;
}

message ContractAcceptResponse {}

// ContractAgreeRequest contains the agreement and pid of the contract negotiation to agree to.
message ContractAgreeRequest {
  string agreement = 1;
  string pid = 2;
  bool auto_accept = 3;
  bool want_notifications = 4;
}

message ContractAgreeResponse {}

// ContractVerifyRequest contains the pid of the contract negotiation to verify.
message ContractVerifyRequest {
  string pid = 1;
  bool auto_accept = 2; // signals to RUN-DSP that it should fast forward the negotiation and not wait for any requests of the contract service.
  bool want_notifications = 3; // signals to RUN-DSP that the contract service still wants notifications only useful if auto_accept is set.
}

message ContractVerifyResponse {}

// ContractFinalizeRequest contains the pid of the contract negotiation to finalize.
message ContractFinalizeRequest {
  string pid = 1;
  bool auto_accept = 2;
  bool want_notifications = 3;
}

message ContractFinalizeResponse {}

// ContractTerminateRequest contains the pid, code, and reason of the contract negotiation to terminate.
message ContractTerminateRequest {
  string pid = 1;
  string code = 2;
  repeated string reason = 3;
}

message ContractTerminateResponse {}

// SignalTransferCompleteRequest is for telling the provider that we are done
// receiving the dataset.
message SignalTransferCompleteRequest {
  string transfer_id = 1;
}

// SignalTransferCompleteResponse is received when we successfully sent a
// transfer complete request.
message SignalTransferCompleteResponse {}

// SignalTransferCancelledRequest is sent when the client wants to cancel a transfer.
message SignalTransferCancelledRequest {
  string transfer_id = 1;
}

// SignalTransferCancelledResponse tells that the cancellation requests was received.
message SignalTransferCancelledResponse {}

// SignalTransferSuspendRequest is sent when the client wishes to pause the transfer.
message SignalTransferSuspendRequest {
  string transfer_id = 1;
}

// SignalTransferSuspendResponse tells the client that the pause request was received.
message SignalTransferSuspendResponse {}

// SignalTransferResumeRequest tells the provider that the client wants to resume transfer.
message SignalTransferResumeRequest {
  string transfer_id = 1;
}

// SignalTransferResumeResponse tells the client that the resume request was accepted.
message SignalTransferResumeResponse {}
